2025-02-04 15:55:11,030 - ERROR - File not found error occurred.
Traceback (most recent call last):
  File "C:\Users\Dnyanesh\AppData\Local\Temp\ipykernel_17996\1498244156.py", line 12, in <module>
    with open("1.txt", "r") as file:
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dnyanesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\IPython\core\interactiveshell.py", line 324, in _modified_open
    return io_open(file, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '1.txt'
